[tool.poetry]
name = "twitch-bot"
version = "1.0.0"
description = "My Twitch channel bot"
authors = ["Amanda Martins Xavier"]
license = "MIT"
readme = "README.md"
packages = [{include = "bot"}]

[tool.poetry.dependencies]
python = "^3.11"
twitchio = "^2.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bot = "bot.bot:run"
